# coap_server.py
# Defines many constants and other goodies related to CoAP

# FIXME: Do we limit ourselves to RFC-7252, or do we also use the updated specifications (such as RFC-8132)? -mario

# Message types
MTYPE_CON = 0
MTYPE_NONCON = 1
MTYPE_ACK = 2
MTYPE_RESET = 3

# Message classes
MCLASS_METHOD = 0
MCLASS_SUCCESS = 2
MCLASS_CLIENT_ERROR = 4
MCLASS_SERVER_ERROR = 5
MCLASS_SIGNAL_CODE = 7

# Empty Message Code
MSG_EMPTY = (0, 0)

# Method Codes
MSG_GET = (0, 1)
MSG_POST = (0, 2)
MSG_PUT = (0, 3)
MSG_DELETE = (0, 4)
MSG_SEARCH = (0, 8)  # This one is non-standard

# Success Codes
MSG_CREATED = (2, 1)
MSG_DELETED = (2, 2)
MSG_VALID = (2, 3)
MSG_CHANGED = (2, 4)
MSG_CONTENT = (2, 5)

# Client Error Codes
MSG_BAD_REQUEST = (4, 0)
MSG_UNAUTHORIZED = (4, 1)
MSG_BAD_OPTION = (4, 2)
MSG_FORBIDDEN = (4, 3)
MSG_NOT_FOUND = (4, 4)
MSG_METHOD_NOT_ALLOWED = (4, 5)
MSG_NOT_ACCEPTABLE = (4, 6)
MSG_REQUEST_ENTITY_INCOMPLETE = (4, 8)
MSG_CONFLICT = (4, 9)
MSG_PRECONDITION_FAILED = (4, 12)
MSG_REQUEST_ENTITY_TOO_LARGE = (4, 13)
MSG_UNSUPPORTED_CONTENT_FORMAT = (4, 15)

# Server Error Codes
MSG_INTERNAL_SERVER_ERROR = (5, 0)
MSG_NOT_IMPLEMENTED = (5, 1)
MSG_BAD_GATEWAY = (5, 2)
MSG_SERVICE_UNAVAILABLE = (5, 3)
MSG_GATEWAY_TIMEOUT = (5, 4)
MSG_PROXYING_NOT_SUPPORTED = (5, 5)

# Signalling Codes
MSG_UNASSIGNED = (7, 0)
MSG_CSM = (7, 1)
MSG_PING = (7, 2)
MSG_PONG = (7, 3)
MSG_RELEASE = (7, 4)
MSG_ABORT = (7, 5)

# Option IDs
OPT_IF_MATCH = 1
OPT_URI_HOST = 3
OPT_ETAG = 4
OPT_IF_NONE_MATCH = 5
OPT_URI_PORT = 7
OPT_LOCATION_PATH = 8
OPT_URI_PATH = 11
OPT_CONTENT_FORMAT = 12
OPT_MAX_AGE = 14
OPT_URI_QUERY = 15
OPT_ACCEPT = 17
OPT_LOCATION_QUERY = 20
OPT_PROXY_URI = 35
OPT_PROXY_SCHEME = 39
OPT_SIZE1 = 60

# List of Critical Options
# Critical Options that fail to parse must raise an error
OPTIONS_CRITICAL = [1, 3, 5, 7, 11, 15, 17, 35, 39]

# List of Repeatable Options
# Options that are repeatable can appear more than once
OPTIONS_REPEATABLE = [1, 4, 8, 11, 15, 20]

# Media types
MEDIA_TEXT = 0
MEDIA_LINK_FORMAT = 40
MEDIA_XML = 41
MEDIA_OCTET_STREAM = 42
MEDIA_EXI = 47
MEDIA_JSON = 50

# Communication parameters
COMM_ACK_TIMEOUT = 2
COMM_ACK_RANDOM_FACTOR = 1.5
COMM_MAX_RETRANSMIT = 4
COMM_NSTART = 1
COMM_DEFAULT_LEISURE = 5
COMM_PROBING_RATE = 1

COMM_MAX_TRANSMIT_SPAN = 45
COMM_MAX_TRANSMIT_WAIT = 93
COMM_MAX_LATENCY = 100
COMM_PROCESSING_DELAY = 2
COMM_MAX_RTT = 202
COMM_EXCHANGE_LIFETIME = 247
COMM_NON_LIFETIME = 145
